### ISSUE TITLE
Automatizare upload de pe Github/cu Jenkins/etc

### ISSUE THREAD

**Issue by mehanix** [as-mi/site-caravana#10]
Ar fi util sa avem deploy automat.

**Comment by GabrielMajeri** [comment]
Cred că se poate rezolva prin GitHub Actions, deocamdată aș putea automatiza un upload prin FTP, dar prefer să aștept să trecem pe Azure unde o să fie mai ușor deploy-ul.

Deocamdată, am un deploy automat configurat prin Netlify pe https://caravana-edu.netlify.com/

**Comment by mehanix** [comment]
done! multumim @GabrielMajeri
