### ISSUE TITLE
Creat subdomeniu caravana

### ISSUE THREAD

**Issue by mehanix** [as-mi/site-caravana#11]
Trebuie creat subdomeniul pentru caravana.
Asta probabil se va face dupa ce schimbam host-ul si domeniul?

**Comment by GabrielMajeri** [comment]
Pot să îl creez de acum, dar probabil că o să fie diferit odată ce trecem la alt host.

**Comment by GabrielMajeri** [comment]
L-am făcut: http://caravana.as-mi.ro
